name: My workflow
on: [push]
jobs:
  run-shell-command:
  steps: 
    - name: echo a string 
      run: echo "Hello World"
    - name: multiline script 
      run: | 
    - name: python Command 
      run: | 
        import platform 
        print(platform.processor())
      shell: python
